### ISSUE TITLE
Проблема с объявлением поля через функцию

### ISSUE THREAD

**Issue by xfynx** [balance-platform/talos#9]
Привет!

Есть некий баг с тем, как через функцию объявляются типы.

Если объявляю так:
```
list(type: integer(gt: 0), allow_blank: false)
```
результат трансформируется в такое (см. allow_blank):
```
%Talos.Types.ListType{
  allow_blank: true,
  allow_nil: false,
  example_value: nil,
  max_length: nil,
  min_length: nil,
  type: %Talos.Types.IntegerType{
    allow_blank: false,
    allow_nil: false,
    example_value: nil,
    gt: 0,
    gteq: nil,
    lt: nil,
    lteq: nil
  }
}
```

Но если через явную структуру:
```
%Talos.Types.ListType{type: integer(gt: 0), allow_blank: false}
```
результат ожидаемый:
```
%Talos.Types.ListType{
  allow_blank: false,
  allow_nil: false,
  example_value: nil,
  max_length: nil,
  min_length: nil,
  type: %Talos.Types.IntegerType{
    allow_blank: false,
    allow_nil: false,
    example_value: nil,
    gt: 0,
    gteq: nil,
    lt: nil,
    lteq: nil
  }
}
```

Навскидку ошибку в коде не вижу, видимо, надо покопаться (возможно, мне самому)

**Comment by sofakingworld** [comment]
Привет, знаю где ошибка, буду рад - если сможешь её исправить

Ошибка в функции   Talos.talos_build_struct

Keyword.get(args, key) || Map.get(type, key)

получается false || true
false - из параметров билдера, а true - значение по умолчанию для стуктуры

**Comment by xfynx** [comment]
сделаем :) на днях постараюсь
